from enum import Enum


class REGION(Enum):
    """Enum of the regions of Gotham City"""

    BLEAK_ISLAND = "BLEAK_ISLAND"
    MIAGANI_ISLAND = "MIAGANI_ISLAND"
    FOUNDER_ISLAND = "FOUNDER_ISLAND"
    OLD_GOTHAM = "OLD_GOTHAM"
    INDUSTRIAL_DISTRICT = "INDUSTRIAL_DISTRICT"
    AMUSEMENT_MILE = "AMUSEMENT_MILE"
    NEW_GOTHAM = "NEW_GOTHAM"
    UNDEFINED = "UNDEFINED"
